// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kDQerCxUJSSgb82xRrAfXFI_BVM--ZQ',
    appId: '1:547234100495:web:657343e313da827d623a7a',
    messagingSenderId: '547234100495',
    projectId: 'school-finder-d64cc',
    authDomain: 'school-finder-d64cc.firebaseapp.com',
    storageBucket: 'school-finder-d64cc.appspot.com',
    measurementId: 'G-DGV7Z74JC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuewXQAveQ4-IFFgLE34SBaeGvy88VCXg',
    appId: '1:547234100495:android:a6dc4d6810e9cd28623a7a',
    messagingSenderId: '547234100495',
    projectId: 'school-finder-d64cc',
    storageBucket: 'school-finder-d64cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ZnSCXG7pvli29WwL5AiuGQ9q670wfXQ',
    appId: '1:547234100495:ios:18cf1d88c9a61965623a7a',
    messagingSenderId: '547234100495',
    projectId: 'school-finder-d64cc',
    storageBucket: 'school-finder-d64cc.appspot.com',
    iosBundleId: 'com.example.schoolFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ZnSCXG7pvli29WwL5AiuGQ9q670wfXQ',
    appId: '1:547234100495:ios:e12de5bb979131af623a7a',
    messagingSenderId: '547234100495',
    projectId: 'school-finder-d64cc',
    storageBucket: 'school-finder-d64cc.appspot.com',
    iosBundleId: 'com.example.schoolFinder.RunnerTests',
  );
}
